allow building from source
matrix-org/matrix-rust-sdk-crypto-nodejs pull request #36
Opened 2024-03-22 20:01 UTC by selfisekai

2024-03-25 08:23 UTC, Hywan reviewed
Oh neat! Thanks for the patch. Looks good so far. What does it need to get out of the draft?

2024-03-25 10:24 UTC, selfisekai commented
i haven't tested it as an npm release yet, just from git

2024-07-27 19:13 UTC, mqudsi commented
It would be nice to have this as a default fallback when prebuilt binaries aren't available for the current platform/architecture.

2026-05-29 11:48 UTC, richvdh requested changes
Sadly this seems to have been bitrotting for two years.

It looks like we should probably merge something similar to this, but I have a few thoughts:

 * Rather than cluttering up the project directory with scripts, is there any reason we can't combine `download-lib.js` and `postinstall.js` into a single file?
 * I'm minded to agree with @mqudsi that it would be nice to fall back to building from source automatically; however this isn't essential provided we document the necessary steps.
 * Either way, the README needs an update.

@selfisekai if you're still out there, do you think you could give this an update?

Otherwise maybe someone else would like to pick up this work?

2026-05-29 11:48 UTC, richvdh commented on postinstall.js
This file needs a comment describing what it does.

2026-07-22 11:00 UTC, richvdh commented
Thanks for your contribution. I'm going to close this for now as the changes requested haven't been made. If you're interested in continuing to work on this please let us know and we can reopen the pull request. Thanks!

2026-07-22 11:00 UTC, closed without merging